# -*- coding: utf-8 -*-
"""Xt2iXaniX0.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zr5lBjG2vPLMWxWOVz9xQ1Z1hVovtMfO
"""

!pip install diffusers --upgrade
!pip install transformers accelerate safetensors

from huggingface_hub import login

login('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')

import torch
from torch import autocast
from diffusers import StableDiffusionXLPipeline, EulerAncestralDiscreteScheduler

device = "cuda"
dtype = torch.float16

model = "linaqruf/animagine-xl"

pipe = StableDiffusionXLPipeline.from_pretrained(
    model,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
    )
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
pipe.to('cuda')

import matplotlib.pyplot as plt
from PIL import Image

# while True:
prompt = "two soldiers wearing a gas masks, clad in military digital camo jungle fatigues, djing on futuristic machines made of mixers, synth, mpc with monitor screens displaying audio waves. colorful hexagon lasers dance through the dark dense foliage of the jungle that breaths with the beat of the music.  a surreal, futuristic atmosphere." #@param {type:"string"}
negative = "text, watermark, copyright, blurry, low resolution, blur, low quality" #@param {type:"string"}
prompt = f"\"{prompt}\""
negative = f"\"{negative}\""
num_steps = 25 #@param {type:"raw"}
guidance_scale = 20 #@param {type:"raw"}
fps = 24 #@param {type:"raw"}
num_frames = 10 #@param {type:"raw"}

output = "Xed.png"

image = pipe(
    prompt,
    width=1280,
    height=720,
    guidance_scale=24,
    num_inference_steps=42
).images[0]

image.save(output)
image = Image.open(output)
plt.imshow(image)
plt.axis('off')
